"use strict";

const bairros = [
	{ nome: "Aarão Reis" },
	{ nome: "Acaba Mundo" },
	{ nome: "Acaiaca" },
	{ nome: "Ademar Maldonado" },
	{ nome: "Aeroporto" },
	{ nome: "Águas Claras" },
	{ nome: "Alípio de Melo" },
	{ nome: "Alpes" },
	{ nome: "Alta Tensão" },
	{ nome: "Alta Tensão I" },
	{ nome: "Alto Barroca" },
	{ nome: "Alto Caiçaras" },
	{ nome: "Alto das Antenas" },
	{ nome: "Alto dos Pinheiros" },
	{ nome: "Alto Vera Cruz" },
	{ nome: "Álvaro Camargos" },
	{ nome: "Ambrosina" },
	{ nome: "Anchieta" },
	{ nome: "Andiroba" },
	{ nome: "Antônio Ribeiro de Abreu" },
	{ nome: "Aparecida" },
	{ nome: "Aparecida Sétima Seção" },
	{ nome: "Ápia" },
	{ nome: "Apolônia" },
	{ nome: "Araguaia" },
	{ nome: "Átila de Paiva" },
	{ nome: "Bacurau" },
	{ nome: "Bairro das Indústrias I" },
	{ nome: "Bairro das Indústrias II" },
	{ nome: "Bairro Novo das Indústrias" },
	{ nome: "Baleia" },
	{ nome: "Bandeirantes" },
	{ nome: "Barão Homem de Melo I" },
	{ nome: "Barão Homem de Melo III" },
	{ nome: "Barão Homem de Melo IV" },
	{ nome: "Barreiro" },
	{ nome: "Barro Preto" },
	{ nome: "Barroca" },
	{ nome: "Beija Flor" },
	{ nome: "Beira-Linha" },
	{ nome: "Bela Vitória" },
	{ nome: "Belém" },
	{ nome: "Belmonte" },
	{ nome: "Belvedere" },
	{ nome: "Bernadete" },
	{ nome: "Betânia" },
	{ nome: "Biquinhas" },
	{ nome: "Bispo de Maura" },
	{ nome: "Boa Esperança" },
	{ nome: "Boa União I" },
	{ nome: "Boa União II" },
	{ nome: "Boa Viagem" },
	{ nome: "Boa Vista" },
	{ nome: "Bom Jesus" },
	{ nome: "Bonfim (HC)" },
	{ nome: "Bonfim (ZN)" },
	{ nome: "Bonsucesso (ZO)" },
	{ nome: "Bonsucesso (ZS)" },
	{ nome: "Brasil Industrial" },
	{ nome: "Braúnas" },
	{ nome: "Buritis" },
	{ nome: "Cabana do Pai Tomás" },
	{ nome: "Cachoeirinha" },
	{ nome: "Caetano Furquim" },
	{ nome: "Caiçara Adelaide" },
	{ nome: "Caiçaras" },
	{ nome: "Calafate" },
	{ nome: "Califórnia" },
	{ nome: "Camargos" },
	{ nome: "Campo Alegre" },
	{ nome: "Camponesa I" },
	{ nome: "Camponesa III" },
	{ nome: "Campus UFMG" },
	{ nome: "Canaã" },
	{ nome: "Canadá" },
	{ nome: "Candelária" },
	{ nome: "Capitão Eduardo" },
	{ nome: "Cardoso" },
	{ nome: "Carlos Prates (HC)" },
	{ nome: "Carlos Prates (ZO)" },
	{ nome: "Carmo" },
	{ nome: "Casa Branca" },
	{ nome: "Castanheira" },
	{ nome: "Castelo" },
	{ nome: "CDI Jatobá" },
	{ nome: "Cenáculo" },
	{ nome: "Centro" },
	{ nome: "Céu Azul" },
	{ nome: "Chácara Leonina" },
	{ nome: "Cidade Jardim" },
	{ nome: "Cidade Jardim Taquaril" },
	{ nome: "Cidade Nova" },
	{ nome: "Cinquentenário" },
	{ nome: "Colégio Batista (HC)" },
	{ nome: "Colégio Batista (ZL)" },
	{ nome: "Comiteco" },
	{ nome: "Concórdia" },
	{ nome: "Cônego Pinheiro" },
	{ nome: "Cônego Pinheiro A" },
	{ nome: "Confisco" },
	{ nome: "Conjunto Bonsucesso" },
	{ nome: "Conjunto Califórnia I" },
	{ nome: "Conjunto Califórnia II" },
	{ nome: "Conjunto Capitão Eduardo" },
	{ nome: "Conjunto Celso Machado" },
	{ nome: "Conjunto Floramar" },
	{ nome: "Conjunto Jardim Filadélfia" },
	{ nome: "Conjunto Jatobá" },
	{ nome: "Conjunto Lagoa" },
	{ nome: "Conjunto Minascaixa" },
	{ nome: "Conjunto Novo Dom Bosco" },
	{ nome: "Conjunto Paulo VI" },
	{ nome: "Conjunto Providência" },
	{ nome: "Conjunto Santa Maria" },
	{ nome: "Conjunto São Francisco de Assis" },
	{ nome: "Conjunto Serra Verde" },
	{ nome: "Conjunto Taquaril" },
	{ nome: "Copacabana" },
	{ nome: "Coqueiros" },
	{ nome: "Coração de Jesus" },
	{ nome: "Coração Eucarístico" },
	{ nome: "Corumbiara" },
	{ nome: "Cruzeiro" },
	{ nome: "Custodinha" },
	{ nome: "Delta" },
	{ nome: "Diamante" },
	{ nome: "Distrito Industrial do Jatobá" },
	{ nome: "Dom Bosco" },
	{ nome: "Dom Cabral" },
	{ nome: "Dom Joaquim" },
	{ nome: "Dom Silvério" },
	{ nome: "Dona Clara" },
	{ nome: "Engenho Nogueira" },
	{ nome: "Ermelinda" },
	{ nome: "Ernesto do Nascimento" },
	{ nome: "Esperança" },
	{ nome: "Esplanada" },
	{ nome: "Estoril" },
	{ nome: "Estrela" },
	{ nome: "Estrela Dalva" },
	{ nome: "Estrela do Oriente" },
	{ nome: "Etelvina Carneiro" },
	{ nome: "Europa" },
	{ nome: "Eymard" },
	{ nome: "Fazendinha" },
	{ nome: "Fernão Dias" },
	{ nome: "Flamengo" },
	{ nome: "Flávio de Oliveira" },
	{ nome: "Flávio Marques Lisboa" },
	{ nome: "Floramar" },
	{ nome: "Floresta (HC)" },
	{ nome: "Floresta (ZL)" },
	{ nome: "Frei Leopoldo" },
	{ nome: "Funcionários" },
	{ nome: "Gameleira" },
	{ nome: "Garças" },
	{ nome: "Glória" },
	{ nome: "Goiânia" },
	{ nome: "Graça" },
	{ nome: "Grajaú" },
	{ nome: "Granja de Freitas" },
	{ nome: "Granja Werneck (ZL)" },
	{ nome: "Granja Werneck (ZN)" },
	{ nome: "Grota" },
	{ nome: "Grotinha" },
	{ nome: "Guanabara" },
	{ nome: "Guarani" },
	{ nome: "Guaratã" },
	{ nome: "Gutierrez" },
	{ nome: "Havaí" },
	{ nome: "Heliópolis" },
	{ nome: "Horto" },
	{ nome: "Horto Florestal" },
	{ nome: "Imbaúbas" },
	{ nome: "Inconfidência" },
	{ nome: "Indaiá" },
	{ nome: "Independência" },
	{ nome: "Ipê" },
	{ nome: "Ipiranga" },
	{ nome: "Itaipu" },
	{ nome: "Itapoã" },
	{ nome: "Itatiaia" },
	{ nome: "Jaqueline" },
	{ nome: "Jaraguá" },
	{ nome: "Jardim Alvorada (ZN)" },
	{ nome: "Jardim Alvorada (ZO)" },
	{ nome: "Jardim América (ZO)" },
	{ nome: "Jardim América (ZS)" },
	{ nome: "Jardim Atlântico" },
	{ nome: "Jardim do Vale" },
	{ nome: "Jardim dos Comerciários" },
	{ nome: "Jardim Felicidade" },
	{ nome: "Jardim Guanabara" },
	{ nome: "Jardim Leblon" },
	{ nome: "Jardim Montanhês" },
	{ nome: "Jardim São José" },
	{ nome: "Jardim Vitória" },
	{ nome: "Jardinópolis" },
	{ nome: "Jatobá" },
	{ nome: "João Alfredo" },
	{ nome: "João Paulo II" },
	{ nome: "João Pinheiro" },
	{ nome: "Jonas Veiga" },
	{ nome: "Juliana" },
	{ nome: "Lagoa" },
	{ nome: "Lagoa da Pampulha" },
	{ nome: "Lagoinha (HC)" },
	{ nome: "Lagoinha (ZN)" },
	{ nome: "Lagoinha Leblon" },
	{ nome: "Lajedo" },
	{ nome: "Laranjeiras" },
	{ nome: "Leonina" },
	{ nome: "Letícia" },
	{ nome: "Liberdade" },
	{ nome: "Lindéia" },
	{ nome: "Lorena" },
	{ nome: "Lourdes" },
	{ nome: "Luxemburgo" },
	{ nome: "Madre Gertrudes" },
	{ nome: "Madri" },
	{ nome: "Mala e Cuia" },
	{ nome: "Manacás" },
	{ nome: "Mangabeiras" },
	{ nome: "Mangueiras" },
	{ nome: "Mantiqueira" },
	{ nome: "Marajó" },
	{ nome: "Maravilha" },
	{ nome: "Marçola" },
	{ nome: "Maria Goretti" },
	{ nome: "Maria Helena" },
	{ nome: "Maria Teresa" },
	{ nome: "Maria Virgínia (ZL)" },
	{ nome: "Maria Virgínia (ZN)" },
	{ nome: "Mariano de Abreu" },
	{ nome: "Marieta I" },
	{ nome: "Marieta II" },
	{ nome: "Marilândia" },
	{ nome: "Mariquinhas" },
	{ nome: "Marmiteiros" },
	{ nome: "Milionários" },
	{ nome: "Minas Brasil" },
	{ nome: "Minascaixa" },
	{ nome: "Minaslândia" },
	{ nome: "Mineirão" },
	{ nome: "Miramar" },
	{ nome: "Mirante" },
	{ nome: "Mirtes" },
	{ nome: "Monsenhor Messias" },
	{ nome: "Monte Azul" },
	{ nome: "Monte São José" },
	{ nome: "Morro dos Macacos" },
	{ nome: "Nazaré" },
	{ nome: "Nossa Senhora da Aparecida" },
	{ nome: "Nossa Senhora da Conceição" },
	{ nome: "Nossa Senhora de Fátima" },
	{ nome: "Nossa Senhora do Rosário" },
	{ nome: "Nova América" },
	{ nome: "Nova Cachoeirinha" },
	{ nome: "Nova Cintra" },
	{ nome: "Nova Esperança" },
	{ nome: "Nova Floresta" },
	{ nome: "Nova Gameleira" },
	{ nome: "Nova Granada (ZO)" },
	{ nome: "Nova Granada (ZS)" },
	{ nome: "Nova Pampulha" },
	{ nome: "Nova Suissa" },
	{ nome: "Nova Vista" },
	{ nome: "Novo Aarão Reis" },
	{ nome: "Novo Glória" },
	{ nome: "Novo Ouro Preto" },
	{ nome: "Novo Santa Cecília" },
	{ nome: "Novo São Lucas" },
	{ nome: "Novo Tupi" },
	{ nome: "Oeste" },
	{ nome: "Olaria" },
	{ nome: "Olhos d'água" },
	{ nome: "Ouro Minas" },
	{ nome: "Ouro Preto" },
	{ nome: "Padre Eustáquio" },
	{ nome: "Palmares (ZL)" },
	{ nome: "Palmares (ZN)" },
	{ nome: "Palmeiras (ZO)" },
	{ nome: "Palmeiras (ZS)" },
	{ nome: "Pantanal" },
	{ nome: "Paquetá" },
	{ nome: "Paraíso" },
	{ nome: "Parque São José" },
	{ nome: "Parque São Pedro" },
	{ nome: "Paulo VI" },
	{ nome: "Pedreira Prado Lopes" },
	{ nome: "Penha" },
	{ nome: "Petropolis" },
	{ nome: "Pilar" },
	{ nome: "Pindorama" },
	{ nome: "Pindura Saia" },
	{ nome: "Pirajá" },
	{ nome: "Piratininga" },
	{ nome: "Pirineus" },
	{ nome: "Planalto" },
	{ nome: "Pompéia" },
	{ nome: "Pongelupe" },
	{ nome: "Pousada Santo Antônio" },
	{ nome: "Prado" },
	{ nome: "Primeiro de Maio" },
	{ nome: "Providência" },
	{ nome: "Renascença" },
	{ nome: "Ribeiro de Abreu" },
	{ nome: "Rio Branco" },
	{ nome: "Sagrada Família" },
	{ nome: "Salgado Filho" },
	{ nome: "Santa Amélia" },
	{ nome: "Santa Branca" },
	{ nome: "Santa Cecília" },
	{ nome: "Santa Cruz (ZL)" },
	{ nome: "Santa Cruz (ZN)" },
	{ nome: "Santa Efigênia (HC)" },
	{ nome: "Santa Efigênia (ZL)" },
	{ nome: "Santa Helena" },
	{ nome: "Santa Inês" },
	{ nome: "Santa Isabel" },
	{ nome: "Santa Lúcia" },
	{ nome: "Santa Margarida" },
	{ nome: "Santa Maria" },
	{ nome: "Santa Mônica" },
	{ nome: "Santa Rita" },
	{ nome: "Santa Rita de Cássia" },
	{ nome: "Santa Rosa" },
	{ nome: "Santa Sofia" },
	{ nome: "Santa Tereza" },
	{ nome: "Santa Terezinha" },
	{ nome: "Santana do Cafezal" },
	{ nome: "Santo Agostinho" },
	{ nome: "Santo André" },
	{ nome: "Santo Antônio" },
	{ nome: "São Benedito" },
	{ nome: "São Bento" },
	{ nome: "São Bernardo" },
	{ nome: "São Cristóvão" },
	{ nome: "São Damião" },
	{ nome: "São Francisco" },
	{ nome: "São Francisco das Chagas" },
	{ nome: "São Gabriel" },
	{ nome: "São Geraldo" },
	{ nome: "São Gonçalo" },
	{ nome: "São João" },
	{ nome: "São João Batista" },
	{ nome: "São Jorge I" },
	{ nome: "São Jorge II" },
	{ nome: "São Jorge III" },
	{ nome: "São José" },
	{ nome: "São Lucas" },
	{ nome: "São Luíz" },
	{ nome: "São Marcos" },
	{ nome: "São Paulo" },
	{ nome: "São Pedro" },
	{ nome: "São Salvador" },
	{ nome: "São Sebastião" },
	{ nome: "São Tomáz" },
	{ nome: "São Vicente" },
	{ nome: "Satélite" },
	{ nome: "Saudade" },
	{ nome: "Savassi" },
	{ nome: "Senhor dos Passos" },
	{ nome: "Serra" },
	{ nome: "Serra do Rola Moça" },
	{ nome: "Serra Verde" },
	{ nome: "Serrano" },
	{ nome: "Silveira" },
	{ nome: "Sion" },
	{ nome: "Solar do Barreiro" },
	{ nome: "Solimões" },
	{ nome: "Sport Club" },
	{ nome: "Sumaré" },
	{ nome: "Suzana" },
	{ nome: "Taquaril" },
	{ nome: "Teixeira Dias" },
	{ nome: "Tiradentes" },
	{ nome: "Tirol" },
	{ nome: "Três Marias" },
	{ nome: "Trevo" },
	{ nome: "Túnel de Ibirité" },
	{ nome: "Tupi A" },
	{ nome: "Tupi B" },
	{ nome: "União" },
	{ nome: "Unidas" },
	{ nome: "Universitário" },
	{ nome: "Universo" },
	{ nome: "Urca" },
	{ nome: "Vale do Jatobá" },
	{ nome: "Várzea da Palma" },
	{ nome: "Venda Nova" },
	{ nome: "Ventosa" },
	{ nome: "Vera Cruz" },
	{ nome: "Vila Aeroporto" },
	{ nome: "Vila Aeroporto Jaraguá" },
	{ nome: "Vila Antena" },
	{ nome: "Vila Antena Montanhês" },
	{ nome: "Vila Átila de Paiva" },
	{ nome: "Vila Bandeirantes" },
	{ nome: "Vila Barragem Santa Lúcia" },
	{ nome: "Vila Batik" },
	{ nome: "Vila Betânia" },
	{ nome: "Vila Boa Vista" },
	{ nome: "Vila Calafate" },
	{ nome: "Vila Califórnia" },
	{ nome: "Vila Canto do Sabiá" },
	{ nome: "Vila CEMIG" },
	{ nome: "Vila Clóris" },
	{ nome: "Vila Copacabana" },
	{ nome: "Vila COPASA" },
	{ nome: "Vila Coqueiral" },
	{ nome: "Vila da Amizade" },
	{ nome: "Vila da Área" },
	{ nome: "Vila da Luz" },
	{ nome: "Vila da Paz" },
	{ nome: "Vila das Oliveiras" },
	{ nome: "Vila de Sá" },
	{ nome: "Vila Dias" },
	{ nome: "Vila do Pombal" },
	{ nome: "Vila dos Anjos" },
	{ nome: "Vila Ecológica" },
	{ nome: "Vila Engenho Nogueira" },
	{ nome: "Vila Esplanada" },
	{ nome: "Vila Formosa" },
	{ nome: "Vila FUMEC" },
	{ nome: "Vila Havaí" },
	{ nome: "Vila Independência I" },
	{ nome: "Vila Independência II" },
	{ nome: "Vila Independência IV" },
	{ nome: "Vila Inestan" },
	{ nome: "Vila Ipiranga" },
	{ nome: "Vila Jardim Alvorada" },
	{ nome: "Vila Jardim Leblon" },
	{ nome: "Vila Jardim Montanhês" },
	{ nome: "Vila Jardim São José" },
	{ nome: "Vila Madre Gertrudes I" },
	{ nome: "Vila Madre Gertrudes II" },
	{ nome: "Vila Madre Gertrudes III" },
	{ nome: "Vila Madre Gertrudes V" },
	{ nome: "Vila Maloca" },
	{ nome: "Vila Mangueiras" },
	{ nome: "Vila Mantiqueira" },
	{ nome: "Vila Maria" },
	{ nome: "Vila Minaslândia" },
	{ nome: "Vila Nossa Senhora Aparecida" },
	{ nome: "Vila Nossa Senhora do Rosário" },
	{ nome: "Vila Nova" },
	{ nome: "Vila Nova Cachoeirinha I" },
	{ nome: "Vila Nova Cachoeirinha II" },
	{ nome: "Vila Nova Cachoeirinha IV" },
	{ nome: "Vila Nova dos Milionários" },
	{ nome: "Vila Nova Gameleira I" },
	{ nome: "Vila Nova Gameleira II" },
	{ nome: "Vila Nova Gameleira III" },
	{ nome: "Vila Nova Paraíso" },
	{ nome: "Vila Novo São Lucas" },
	{ nome: "Vila Oeste" },
	{ nome: "Vila Olhos d'água" },
	{ nome: "Vila Ouro Minas" },
	{ nome: "Vila Paquetá" },
	{ nome: "Vila Paraíso" },
	{ nome: "Vila Paris" },
	{ nome: "Vila Petrópolis" },
	{ nome: "Vila Pilar" },
	{ nome: "Vila Pinho" },
	{ nome: "Vila Piratininga" },
	{ nome: "Vila Piratininga Venda Nova" },
	{ nome: "Vila Primeiro de Maio" },
	{ nome: "Vila PUC" },
	{ nome: "Vila Real I" },
	{ nome: "Vila Real II" },
	{ nome: "Vila Rica" },
	{ nome: "Vila Santa Mônica" },
	{ nome: "Vila Santa Rosa" },
	{ nome: "Vila Santo Antônio" },
	{ nome: "Vila Santo Antônio Barroquinha" },
	{ nome: "Vila São Dimas" },
	{ nome: "Vila São Francisco" },
	{ nome: "Vila São Gabriel" },
	{ nome: "Vila São Gabriel Jacuí" },
	{ nome: "Vila São Geraldo" },
	{ nome: "Vila São João Batista" },
	{ nome: "Vila São Paulo" },
	{ nome: "Vila São Rafael" },
	{ nome: "Vila Satélite" },
	{ nome: "Vila SESC" },
	{ nome: "Vila Sumaré" },
	{ nome: "Vila Suzana I" },
	{ nome: "Vila Suzana II" },
	{ nome: "Vila Tirol" },
	{ nome: "Vila Trinta e Um de Março" },
	{ nome: "Vila União" },
	{ nome: "Vila Vera Cruz I" },
	{ nome: "Vila Vera Cruz II" },
	{ nome: "Vila Vista Alegre" },
	{ nome: "Virgínia" },
	{ nome: "Vista Alegre" },
	{ nome: "Vista do Sol" },
	{ nome: "Vitória" },
	{ nome: "Vitória da Conquista" },
	{ nome: "Xangri-lá" },
	{ nome: "Xodó-Marize" },
	{ nome: "Zilah Spósito" }
];

module.exports = {
	/**
	 * Função de aplicação da semente
	 * @param {import("sequelize").QueryInterface} queryInterface
	 * @param {import("sequelize").DataTypes} Sequelize
	 */
	up: async (queryInterface, Sequelize) => {
		await queryInterface.bulkInsert("bairros", bairros);
	},

	/**
	 * Função que desfaz a aplicação da semente
	 * @param {import("sequelize").QueryInterface} queryInterface
	 * @param {import("sequelize").Sequelize} Sequelize
	 */
	down: async (queryInterface, Sequelize) => {
		await queryInterface.bulkDelete("bairros", {
			nome: bairros.map(b => b.nome)
		});
	}
};
